/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_victorcruz;

import javax.swing.DefaultListModel;

/**
 *
 * @author Victor Jafet Cruz
 */
public class Examen2P2_VictorCruz extends javax.swing.JFrame {

    /**
     * Creates new form Examen2P2_VictorCruz
     */
    public Examen2P2_VictorCruz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_AdminCarros = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_ListarCarros = new javax.swing.JTable();
        JB_ModificarCarro = new javax.swing.JButton();
        JB_EliminarCarros = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JD_AdminBateria = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_ListarCarros1 = new javax.swing.JTable();
        JB_ModificarCarro1 = new javax.swing.JButton();
        JB_EliminarCarros1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JD_MenuSimulacion = new javax.swing.JDialog();
        JB_EsamblarBaterias = new javax.swing.JButton();
        JB_GenerarReporteEnsamblaje = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_BateriaEnsamblaje = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_CarrosEnsamblados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JD_Ensamblaje = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        JL_BateriaActual = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        JL_CarroActual = new javax.swing.JLabel();
        PB_Ensamblaje = new javax.swing.JProgressBar();
        JB_IniciarEsamblaje = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JT_SimulacionEnsamblaje = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        JB_SalirDelSistema = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_AdminCarrosBateria = new javax.swing.JMenu();
        JMI_AdminCarros = new javax.swing.JMenuItem();
        JMI_AdminBateria = new javax.swing.JMenuItem();
        JM_SimulacionHilo = new javax.swing.JMenu();
        JMI_SimulacionHilo = new javax.swing.JMenuItem();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("Administracion Carros");

        JT_ListarCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "VIN", "Modelo", "Tipo de Carroceria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JT_ListarCarros);

        JB_ModificarCarro.setText("Modificar");

        JB_EliminarCarros.setText("Eliminar");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Listar Carros");

        javax.swing.GroupLayout JD_AdminCarrosLayout = new javax.swing.GroupLayout(JD_AdminCarros.getContentPane());
        JD_AdminCarros.getContentPane().setLayout(JD_AdminCarrosLayout);
        JD_AdminCarrosLayout.setHorizontalGroup(
            JD_AdminCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdminCarrosLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel3)
                .addContainerGap(516, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdminCarrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JD_AdminCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(JD_AdminCarrosLayout.createSequentialGroup()
                        .addComponent(JB_ModificarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_EliminarCarros))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        JD_AdminCarrosLayout.setVerticalGroup(
            JD_AdminCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdminCarrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_AdminCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_EliminarCarros)
                    .addComponent(JB_ModificarCarro))
                .addGap(55, 55, 55))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setText("Administracion Baterias");

        JT_ListarCarros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Capacidad Bateria", "Tipo de Vehiculo", "Tiempo de Ensamblaje", "Autonomia", "Capacidad Carga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(JT_ListarCarros1);

        JB_ModificarCarro1.setText("Modificar");

        JB_EliminarCarros1.setText("Eliminar");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Listar Bateria");

        javax.swing.GroupLayout JD_AdminBateriaLayout = new javax.swing.GroupLayout(JD_AdminBateria.getContentPane());
        JD_AdminBateria.getContentPane().setLayout(JD_AdminBateriaLayout);
        JD_AdminBateriaLayout.setHorizontalGroup(
            JD_AdminBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdminBateriaLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel5)
                .addContainerGap(505, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdminBateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JD_AdminBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(JD_AdminBateriaLayout.createSequentialGroup()
                        .addComponent(JB_ModificarCarro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_EliminarCarros1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        JD_AdminBateriaLayout.setVerticalGroup(
            JD_AdminBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdminBateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_AdminBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_EliminarCarros1)
                    .addComponent(JB_ModificarCarro1))
                .addGap(55, 55, 55))
        );

        JB_EsamblarBaterias.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JB_EsamblarBaterias.setText("Ensamblar Baterias");
        JB_EsamblarBaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EsamblarBateriasMouseClicked(evt);
            }
        });

        JB_GenerarReporteEnsamblaje.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JB_GenerarReporteEnsamblaje.setText("Generar Reporte");
        JB_GenerarReporteEnsamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_GenerarReporteEnsamblajeMouseClicked(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel54.setText("recuerde seleccionar ambas listas para el ensamblaje");

        JL_BateriaEnsamblaje.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(JL_BateriaEnsamblaje);

        JL_CarrosEnsamblados.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(JL_CarrosEnsamblados);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Carros");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Bateria");

        javax.swing.GroupLayout JD_MenuSimulacionLayout = new javax.swing.GroupLayout(JD_MenuSimulacion.getContentPane());
        JD_MenuSimulacion.getContentPane().setLayout(JD_MenuSimulacionLayout);
        JD_MenuSimulacionLayout.setHorizontalGroup(
            JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                        .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel54))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_GenerarReporteEnsamblaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_EsamblarBaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_MenuSimulacionLayout.setVerticalGroup(
            JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addGap(11, 11, 11)
                .addComponent(JB_EsamblarBaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_GenerarReporteEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel47.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel47.setText("Bareria seleccionada:");

        JL_BateriaActual.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel48.setText("Carro seleccionado:");

        JL_CarroActual.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        PB_Ensamblaje.setString("");
        PB_Ensamblaje.setStringPainted(true);

        JB_IniciarEsamblaje.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JB_IniciarEsamblaje.setText("Iniciar");
        JB_IniciarEsamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_IniciarEsamblajeMouseClicked(evt);
            }
        });

        JT_SimulacionEnsamblaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza ensamblada", "Tiempo que se tardo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(JT_SimulacionEnsamblaje);

        javax.swing.GroupLayout JD_EnsamblajeLayout = new javax.swing.GroupLayout(JD_Ensamblaje.getContentPane());
        JD_Ensamblaje.getContentPane().setLayout(JD_EnsamblajeLayout);
        JD_EnsamblajeLayout.setHorizontalGroup(
            JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JL_BateriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_CarroActual, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_EnsamblajeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PB_Ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_EnsamblajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_IniciarEsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        JD_EnsamblajeLayout.setVerticalGroup(
            JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel47))
                        .addComponent(JL_CarroActual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JL_BateriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PB_Ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JB_IniciarEsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        JB_SalirDelSistema.setText("Salir de Sistema");
        JB_SalirDelSistema.setFocusable(false);
        JB_SalirDelSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirDelSistema.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_SalirDelSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirDelSistemaMouseClicked(evt);
            }
        });
        jToolBar1.add(JB_SalirDelSistema);

        JM_AdminCarrosBateria.setText("Admin Carros/ Bateria");

        JMI_AdminCarros.setText("Admin Carros");
        JMI_AdminCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AdminCarrosActionPerformed(evt);
            }
        });
        JM_AdminCarrosBateria.add(JMI_AdminCarros);

        JMI_AdminBateria.setText("Admin Bateria");
        JMI_AdminBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AdminBateriaActionPerformed(evt);
            }
        });
        JM_AdminCarrosBateria.add(JMI_AdminBateria);

        jMenuBar1.add(JM_AdminCarrosBateria);

        JM_SimulacionHilo.setText("Simulacion Hilo");

        JMI_SimulacionHilo.setText("Simulacion");
        JMI_SimulacionHilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SimulacionHiloActionPerformed(evt);
            }
        });
        JM_SimulacionHilo.add(JMI_SimulacionHilo);

        jMenuBar1.add(JM_SimulacionHilo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 440, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_SalirDelSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirDelSistemaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_SalirDelSistemaMouseClicked

    private void JMI_AdminCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AdminCarrosActionPerformed
        AdminCarros();
    }//GEN-LAST:event_JMI_AdminCarrosActionPerformed

    private void JMI_AdminBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AdminBateriaActionPerformed
        // TODO add your handling code here:
        AdminBateria();
    }//GEN-LAST:event_JMI_AdminBateriaActionPerformed

    private void JMI_SimulacionHiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SimulacionHiloActionPerformed
        MenuEnsamblaje();
    }//GEN-LAST:event_JMI_SimulacionHiloActionPerformed

    private void JB_EsamblarBateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EsamblarBateriasMouseClicked
        // TODO add your handling code here:
        /*DefaultListModel modelo = (DefaultListModel) JL_ComputadorasEnsamblajes.getModel();
        DefaultListModel modelo2 = (DefaultListModel) JL_TecnicosEnsamblaje.getModel();
        String computadora = ((Computadora) modelo.getElementAt(JL_ComputadorasEnsamblajes.getSelectedIndex())).getSerie();
        String tecnico = ((Tecnico) modelo2.getElementAt(JL_TecnicosEnsamblaje.getSelectedIndex())).getNombre();
        JL_ComputadoraActual.setText(computadora);
        JL_TecnicoActual.setText(tecnico);
        SimulacionEnsamblaje();*/
    }//GEN-LAST:event_JB_EsamblarBateriasMouseClicked

    private void JB_GenerarReporteEnsamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_GenerarReporteEnsamblajeMouseClicked
        // TODO add your handling code here:
        //me escuchas????
        /*DefaultTableModel modelo3 = (DefaultTableModel) JT_SimulacionEnsamblaje.getModel();
        for (int i = 0; i < JT_SimulacionEnsamblaje.getRowCount(); i++) {
            Object r = modelo3.getValueAt(i, 0);
            Object r1 = modelo3.getValueAt(i, 1);
            rep += "\nPieza Ensamblada:" + r + " Tiempo: " + r1 + "\n";

        }
        rep += "\n";
        System.out.println(rep);
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro
        = new FileNameExtensionFilter(
            "Archivos de texto", "txt");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals(
                    "Archivos de texto")) {
                fichero
                = new File(jfc.getSelectedFile().getPath() + ".txt");
            } else {
                fichero = jfc.getSelectedFile();
            }

            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);

            Object f = rep;
            bw.writeObject(f);
            bw.flush();
            //Ya

            JOptionPane.showMessageDialog(JD_MenuEnsamblaje,
                "Archivo guardado exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
        }*/
    }//GEN-LAST:event_JB_GenerarReporteEnsamblajeMouseClicked

    private void JB_IniciarEsamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_IniciarEsamblajeMouseClicked
        // TODO add your handling code here:

        /*DefaultListModel modelo = (DefaultListModel) JL_ComputadorasEnsamblajes.getModel();
        DefaultTableModel m = (DefaultTableModel) JT_SimulacionEnsamblaje.getModel();
        DefaultListModel n = (DefaultListModel) JL_TecnicosEnsamblaje.getModel();
        Tecnico t = ((Tecnico) n.getElementAt(JL_TecnicosEnsamblaje.getSelectedIndex()));
        t.setCantidad_computadoras(t.getCantidad_computadoras() + 1);
        Computadora c = ((Computadora) modelo.getElementAt(JL_ComputadorasEnsamblajes.getSelectedIndex()));
        adminBarra ab = new adminBarra(PB_Ensamblaje, c, JT_SimulacionEnsamblaje);
        ab.start();
        ab.Tabla();
        int s;
        if (t.getCantidad_computadoras() < 6) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 31) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }//fin del if
        }//fin de la condicion
        else if (t.getCantidad_computadoras() >= 6 && t.getCantidad_computadoras() < 15) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 22) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }//fin del if
        }//fin del condicion
        else if (t.getCantidad_computadoras() >= 15 && t.getCantidad_computadoras() < 31) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 13) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }
        } else if (t.getCantidad_computadoras() >= 31) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 7) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }
        }
        */
    }//GEN-LAST:event_JB_IniciarEsamblajeMouseClicked

    
    public void AdminCarros() {
        JD_AdminCarros.pack();
        JD_AdminCarros.setModal(true);
        JD_AdminCarros.setLocationRelativeTo(this);
        JD_AdminCarros.setVisible(true);
    }

    public void AdminBateria() {
        JD_AdminBateria.pack();
        JD_AdminBateria.setModal(true);
        JD_AdminBateria.setLocationRelativeTo(this);
        JD_AdminBateria.setVisible(true);
    }

    public void Ensamblaje() {
        JD_Ensamblaje.pack();
        JD_Ensamblaje.setModal(true);
        JD_Ensamblaje.setLocationRelativeTo(this);
        JD_Ensamblaje.setVisible(true);
    }
    
    public void MenuEnsamblaje() {
        JD_MenuSimulacion.pack();
        JD_MenuSimulacion.setModal(true);
        JD_MenuSimulacion.setLocationRelativeTo(this);
        JD_MenuSimulacion.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2P2_VictorCruz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_EliminarCarros;
    private javax.swing.JButton JB_EliminarCarros1;
    private javax.swing.JButton JB_EsamblarBaterias;
    private javax.swing.JButton JB_GenerarReporteEnsamblaje;
    private javax.swing.JButton JB_IniciarEsamblaje;
    private javax.swing.JButton JB_ModificarCarro;
    private javax.swing.JButton JB_ModificarCarro1;
    private javax.swing.JButton JB_SalirDelSistema;
    private javax.swing.JDialog JD_AdminBateria;
    private javax.swing.JDialog JD_AdminCarros;
    private javax.swing.JDialog JD_Ensamblaje;
    private javax.swing.JDialog JD_MenuSimulacion;
    private javax.swing.JLabel JL_BateriaActual;
    private javax.swing.JList<String> JL_BateriaEnsamblaje;
    private javax.swing.JLabel JL_CarroActual;
    private javax.swing.JList<String> JL_CarrosEnsamblados;
    private javax.swing.JMenuItem JMI_AdminBateria;
    private javax.swing.JMenuItem JMI_AdminCarros;
    private javax.swing.JMenuItem JMI_SimulacionHilo;
    private javax.swing.JMenu JM_AdminCarrosBateria;
    private javax.swing.JMenu JM_SimulacionHilo;
    private javax.swing.JTable JT_ListarCarros;
    private javax.swing.JTable JT_ListarCarros1;
    private javax.swing.JTable JT_SimulacionEnsamblaje;
    private javax.swing.JProgressBar PB_Ensamblaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
